#Plugin: XPBoost
#Author: Qifi (elving21)
#The variables which start and end with '%' you can either move them around or comepletely remove from the message
settings:
  config_version: 1
  #can be ENG atm only, if you've got a translation to some other language sent it to me and i will include it :)
  language: 'ENG'
  #Enable debug 0 = disabled | 1 = Normal | 2 = All information (Mostly useless)
  debug: 0
  #this is in development (faction support), please use it at your own risk.
  enable_factions: false
  #If you dont want to send metrics (statistics about the plugin) cahnge it to false
  metrics: true
  #Do you want to disable xp bottles? SELECT MODE 1 or 2 or 3
  #Mode 1: Normal behaviour
  #Mode 2: Set dropped XP from xp bottles to 0
  #Mode 3: Disallow players to drop EXP bottles while their boost is active
  xpbottlemode: 1
  #if you want to use only SkillAPI/McMmmo/Heroes/RpgMe etc. experience for example, set this to true, and vanilla xp will be unaffected
  disablevanillaxp: false
  globalboost:
    #Global XP boost
    multiplier: 2.0
    #Enable/disable notification on join when global boost is active
    notification: true
  #Do you want the message about the XP gained to appear
  doublexpmsg: true
  #Actionban msg time delay in ticks, (20 ticks = 1 sec) default 5 sec
  actiondelay: 100
  #Enable/disable motd when global boost is active
  motdon: true
  #Enable/disable actionbar message when boost is active
  actionbarmsg: true
  bossbar:
    #Enable/disable bossbar when boost is active (will work only if BossBar plugin is present)
    bossbarmsg: true
    #Color of the boss bar
    color: BLUE
    #Style of the boss bar
    style: NOTCHED_20
  #Item type material for an xpboost item from /xpb item
  itemmaterial: POTION
  #Sign settings
  sign:
    #line1 is the text that u need to write in order to create sign, other lines will apear automatically
    line1: '&a[XPBoost]'
    line2: '&cOpen'
    #if you dont need other lines, just leave it blank
    line3: ''
    line4: ''
  #Days on which XP boost should be active for everyone! (change to true)
  day:
    monday: false
    teusday: false
    wednesday: false
    thursday: false
    friday: false
    saturday: false
    sunday: false
  #Disabled commands
  disabledcommands:
    #Do you want this feature to be enabled?
    enabled: true
    #List of forbiden commands while XPBoost is active
    list:
    - '/give'
    - '/test'
  #Put it to true if you are using daily global xpboost and ur server does not restart every day
  periodicalDayCheck: false
  #McMMO support
  mcmmo:
    msg:
      enabled: true
      msg: '&aGained &c%newexp% &aXP instead of &c%oldexp%&a. Skill: &c%skill%'
  #RPGme support
  rpgme:
    msg:
      enabled: true
      #I disabled message for a STAMINA skill cuz its just spamms rly a lot
      msg: '&aGained &c%newexp% &aXP instead of &c%oldexp%&a. Skill: &c%skill%'
  #Heroes support
  heroes:
    msg:
      enabled: true
      msg: '&aGained &c%newexp% &aXP instead of &c%oldexp%&a. Source: &c%source%'
  #JobsReborn support
  jobs:
    msg:
      enabled: true
      msg: '&aGained &c%newexp% &aXP instead of &c%oldexp%&a. Job: &c%job%'
#
#
#########################################################
# EXAMPLE BOOST (And all possible values you can change)
#########################################################
#
#boost:
#  boost1:
#   enabled: true #|Enable or disable boost option *REQUIRED*
#   boost: 2.0 #|XP multiplier *REQUIRED*
#   cost: 500.0 #|Currency cost *REQUIRED*
#   time: 300 #|Duration of the effect in seconds *REQUIRED*
#   title: '&4%boost%x XPBoost &f(%money% $) Custom Title' #|You can specify custom titles for different boosts if title is not present default preset will be used Placeholders: %boost%,%money%,%time% *OPTIONAL*
#   item_type: SLIME_BALL #|*OPTIONAL*
#   lore: #|Yep, you can set custom lore for the boost, this is optional. If lore is not set, default preset will be used.
#   - 'Boost with custom lore'
#   - '%boost%x for %time% Seconds' #| %boost%, %money% and %time% placeholders are avaliable inside lore.
#   permisson: #|*REQUIRED*
#     use: false #|Enable or disable permission usage for boost
#     perm: 'xpboost.guest' #|if use=true, this permission is required to buy this boost
#     msg: '&cNo permission' #|Message when player does not have a permission
#   behaviour:  #|You can specify a 'behaviour' of each boost and set which XP will be affected, this is optional. Default everything is true *OPTIONAL*
#     VANILLA: true  #|This XP Boost will be only viable for vanilla xp.
#     SKILLAPI: false #|This XP boost will be disabled for skillapi if you've got one.
#     MCMMO: false #|Same but for mcmmo
#     RPGME: false #|Same but for rgme
#     HEROES: false #|Same but for heroes
#     JOBS: false #|Same but for JobsReborn
#   advanced: *OPTIONAL*
#    //Here you can set specifically what kind of exp you want to be affected. The format is: plugin_name.type_of_exp (eg: skillapi.craft | mcmmo.alchemy | heroes.farming)
#    //If nothing is set here, all experience will be affected otherwise it will affect only the ones that are listed below.
#    //If you wish to block some type of experience just add ' block' at the end.
#    - 'skillapi.block_place' //this boost will affect only exp gained from block placing from skillapi (other experience from skillapi will not be boosted)
#    - 'heroes.farming' //this boost will affect only exp gained from farming from heroes (other experience from heroes will not be boosted)
#    - 'mcmmo.excavation block' #this boost will not affect excavation exp from mcmmo 
#
#
#

boost:
  boost1:
    enabled: true
    boost: 1.5
    cost: 500.0
    time: 300
    title: '&4%boost%x XPBoost &f(%money% $) Custom Title'
    item_type: SLIME_BALL
    lore:
    - 'Boost with custom lore'
    - '%boost%x for %time% Seconds'
    permission:
      use: false
      perm: 'xpboost.guest'
      msg: '&cNo permission (%perm%)'
    behaviour:
      VANILLA: true
      SKILLAPI: false
      HEROES: true
      JOBS: true
      MCMMO: true
    advanced:
      #Here you can choose specifically what kind of experience will be affected by the boost
      SKILLAPI: #this boost will ignore crafting experience from SKILLAPI
        default: true
        crafting: false
      MCMMO: #this boost will ONLY affect EXCAVATION experience from mcmmo
        default: false
        excavation: true
      HEROES: #this boost will ignore farming and killing experience from HEROES
        farming: false
        killing: false
  boost2:
    enabled: true
    boost: 2.0
    cost: 800.0
    time: 250
    permission:
      use: false
      perm: 'xpboost.guest'
      msg: '&cNo permission (%perm%)'
    behaviour:
      SKILLAPI: false
      RPGME: false
  boost3:
    enabled: true
    boost: 2.5
    cost: 1500
    time: 350
    permission:
      use: true
      perm: 'xpboost.vip'
      msg: '&cThis boost is only for &aVIP &cusers. (%perm%)'
    behaviour:
      VANILLA: true
      SKILLAPI: false
      MCMMO: true
      RPGME: false
  boost4:
    enabled: true
    boost: 3.0
    cost: 3000.0
    time: 350
    permission:
      use: true
      perm: 'xpboost.vip'
      msg: '&cThis boost is only for &aVIP &cusers. (%perm%)'
  boost5:
    enabled: true
    boost: 3.5
    cost: 5000.0
    time: 1000
    permission:
      use: true
      perm: 'xpboost.vip'
      msg: '&cThis boost is only for &aVIP &cusers. (%perm%)'
  boost6:
    enabled: false
    boost: 4.0
    cost: 7000.0
    time: 300
    permission:
      use: true
      perm: 'xpboost.mod'
      msg: '&cThis boost is only for &aMOD &cusers. (%perm%)'
  boost7:
    enabled: false
    boost: 5.0
    cost: 10000.0
    time: 300
    permission:
      use: true
      perm: 'xpboost.mod'
      msg: '&cThis boost is only for &aMOD &cusers. (%perm%)'