name: XPboost
author: Qifi (elving21)
version: 1.95
main: cz.dubcat.xpboost.Main
commands:
    xpboost:
        description: Main command.
        aliases: [xpb]
        permission: xpboost.use
        permission-message: '§cYou do not have permission to use this command'
permissions:
    xpboost.use:
        description: Allows you to use the plugin
        default: op
    xpboost.admin:
        description: Allows you to use the admin commands
        default: op
depend: [Vault]
softdepend: [Vault,SkillAPI,RPGme,BossBarAPI,Heroes,PlaceholderAPI,Factions,MVdWPlaceholderAPI]